---
# tasks file for ansible-role-find-package
- name: use single package
  include: single_package.yml
  when: ( package_list | length ) == 0

- name: use multi package
  include: multi_package.yml
  when: package_list | length
